# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_github_session": "01_stats.ipynb",
         "OrgStats": "01_stats.ipynb",
         "get_repos": "01_stats.ipynb",
         "repos": "01_stats.ipynb",
         "repo_count": "01_stats.ipynb",
         "public_repos": "01_stats.ipynb",
         "public_repo_count": "01_stats.ipynb",
         "private_repos": "01_stats.ipynb",
         "private_repo_count": "01_stats.ipynb",
         "get_repo_files": "01_stats.ipynb",
         "get_org_files": "01_stats.ipynb",
         "files": "01_stats.ipynb",
         "files_public": "01_stats.ipynb",
         "files_private": "01_stats.ipynb",
         "get_ext": "01_stats.ipynb",
         "get_repo_file_ext_frequency": "01_stats.ipynb",
         "get_org_file_ext_frequency": "01_stats.ipynb",
         "get_org_snapshot_stats": "01_stats.ipynb",
         "snapshot_stats": "01_stats.ipynb",
         "get_repo_views_traffic": "01_stats.ipynb",
         "get_org_views_traffic": "01_stats.ipynb",
         "get_repo_clones_traffic": "01_stats.ipynb",
         "get_org_clones_traffic": "01_stats.ipynb"}

modules = ["stats.py"]

doc_url = "https://Living-with-machines.github.io/gh_orgstats/"

git_url = "https://github.com/Living-with-machines/gh_orgstats/tree/master/"

def custom_doc_links(name): return None
